steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "gcp/Dockerfile.train"
      - "-t"
      - "${_IMAGE}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_IMAGE}"

images:
  - "${_IMAGE}"

substitutions:
  _IMAGE: "us-east1-docker.pkg.dev/$PROJECT_ID/rav-train/rav-chest:latest"

options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: 100

timeout: "3600s"
