name: Manually auto-approve PR

on:
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: 'PR number to approve'
        required: true
        type: string

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ inputs.pullRequestNumber }}
